---

- name: Install EPEL repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Install Nginx repo
  yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm state=present

- name: Install webtatic repo
  yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

- name: Upgrade all packages
  yum: name=* state=latest

- name: Install Git
  yum: name=git state=present

- name: Install wget
  yum: name=wget state=present

- name: Install latest nginx
  yum: name=nginx state=present

- name: Automatic load when boot
  command: systemctl enable nginx.service
  tags:
      - packages

- name: Copy Nginx Main configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0644

- name: Copy Nginx Options configuration
  template: src=options.conf.j2 dest=/etc/nginx/options.conf mode=0644

#- name: Copy www default configuration
#  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf mode=0644
- name: Copy  configuration in place.
  template:
    src: def.conf.j2
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
     - restart restart nginx

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes

- name: Change SELinux Policy Mode
  selinux: state=disabled
  ignore_errors: True
