---
- name: Launch Instance
  ec2:
    group: "{{group}}"
    count: 1
    instance_type: "{{ instance_type}}"
    image: '{{image}}'
    wait: true
    region: "{{region}}"
    keypair: '{{ keypair }}'
    instance_tags: '{ "Name":"{{ hostname }}" , "Group":"db-server" }'
  register: ec2

- add_host: hostname={{ item.public_ip }} groupname=ec2host-db
  with_items: ec2.instances

- name: wait for instances to listen on port:22
  wait_for:
        state=started
        host={{ item.public_dns_name }}
        port=22
  with_items: ec2.instances

